version: '3'

services:
  mysqldb:
    image: mysql:8.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stockschema
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3307:3306

  app:
    depends_on:
      - mysqldb
    image: demostockapp:latest
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stockschema?useSSL=false
      - spring.datasource.username=admin
      - spring.datasource.password=admin
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.servlet.multipart.enabled=true
      - spring.servlet.multipart.max-file-size=2MB
      - spring.servlet.multipart.max-request-size=2MB
      - logging.level.com.example.demostockapp=INFO
      - logging.pattern.console=%d [%level] %c{1.} [%t] %m%n
      - logging.file=stockapplog.log
      - logging.pattern.file=%d [%level] %c{1.} [%t] %m%n

